---
- name: Patch LIRC install for PiKVM
  vars_files:
    - "../vars.yaml"
  hosts: all
  handlers:
    - import_tasks: ../handlers.yaml
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - lirc
